#!/usr/bin/env python3
"""The plugin pet's pictures, drawn pixel by pixel at their real size (20 x 12 pixels, six text rows).

A pet is put together from parts: a body for its stage of life, a face for its mood, something it wears,
and things floating around it. The plugin does the putting together while it runs; this file only holds
the parts. Edit the pictures, then run from the repository root:

    python3 claude-plugin/build.py                 writes the parts into the plugin and the board page, and redraws docs/*.png
    python3 claude-plugin/build.py sheet.png       also saves a picture of every stage, mood and item
"""
import json
import struct
import sys
import zlib
from pathlib import Path

COLORS = {
    "O": (112, 58, 44), "B": (226, 136, 100), "L": (255, 238, 220), "E": (38, 30, 52), "W": (255, 255, 255),
    "P": (255, 150, 160), "M": (120, 30, 54), "T": (246, 122, 142), "y": (255, 214, 10), "c": (64, 224, 208),
    "v": (170, 130, 255), "Z": (170, 205, 255), "G": (176, 176, 190), "g": (96, 96, 112), "S": (130, 205, 255),
    "D": (176, 74, 58), "j": (110, 200, 90), "F": (255, 120, 40), "R": (226, 60, 70), "K": (60, 60, 76),
}
# Other coats: each one swaps some of the colours above.
COATS = {
    "fainted": {"B": (176, 176, 190), "O": (96, 96, 112), "L": (214, 214, 224), "P": (176, 176, 190), "D": (140, 140, 156)},
    "shiny": {"B": (112, 196, 255), "O": (40, 70, 140), "D": (70, 120, 220), "P": (255, 170, 210)},
    "legend": {"L": (255, 232, 150), "D": (255, 196, 40)},
}


# A pet is one of two bodies: the baby, and the grown one every later stage shares.
# The face goes in the four rows starting at "face", columns 3 to 16. "lift" is how much lower a baby wears things.
BODIES = {
    "baby": {"face": 5, "lift": 1, "art": """
....................
....................
.........O..........
....OOOOOOOOOOOO....
...OBBBBBBBBBBBBO...
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
...OBBLLLLLLLLBBO...
....OOOOOOOOOOOO....
....................
"""},
    "grown": {"face": 4, "lift": 0, "art": """
....................
....................
...OOOOOOOOOOOOOO...
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
..OBBBBBBBBBBBBBBO..
..OBBBLLLLLLLLBBBO..
...OBBLLLLLLLLBBO...
...OOBBBBBBBBBBOO...
....OO.OOOOOO.OO....
"""},
}

# What growing up adds, drawn over the grown body: a tail for a teen, wings as well for an adult.
GROWTH = {
    "teen": """
....................
....................
....................
....................
....................
...................L
...................O
...................O
...................O
.................OO.
""",
    "adult": """
....................
....................
....................
D..................D
DD................DD
DD................DD
.D................D.
....................
...................D
..................D.
""",
}

# The animals. Each is a coat (its own colours for the body letters), a top drawn over the head of a grown pet,
# and sometimes a few pixels drawn after the face. In "after", an underscore rubs a pixel out.
SPECIES = {
    "blob": {"coat": {}, "top": """
....OO........OO....
...OBBO......OBBO...
...OBBB......BBBO...
"""},
    "cat": {"coat": {"B": (178, 176, 200), "O": (78, 72, 104), "L": (242, 240, 250), "D": (120, 114, 156)}, "top": """
...O............O...
...OBO........OBO...
...OBPB......BPBO...
"""},
    "bunny": {"coat": {"B": (255, 232, 238), "O": (172, 108, 132), "L": (255, 255, 255), "D": (236, 150, 178)}, "top": """
....OBO......OBO....
....OPO......OPO....
....OPO......OPO....
"""},
    "duck": {"coat": {"B": (255, 216, 92), "O": (158, 104, 30), "L": (255, 244, 204), "D": (240, 160, 40)}, "top": """
..........O.........
.........OBO........
.........BBB........
""", "after": """
....................
....................
....................
....................
....................
....................
........FFFF........
.........FF.........
"""},
    "cactus": {"coat": {"B": (122, 198, 106), "O": (44, 104, 62), "L": (192, 234, 162), "D": (70, 150, 80)}, "top": """
.........PP.........
........PyyP........
.........PP.........
""", "after": """
....................
....................
....................
......O......O......
....................
....................
....................
....................
....O..........O....
"""},
    "ghost": {"coat": {"B": (238, 238, 250), "O": (128, 124, 168), "L": (255, 255, 255), "P": (255, 176, 196), "D": (190, 190, 232)}, "top": """
....................
....................
....................
""", "after": """
....................
....................
....................
....................
....................
....................
....................
....................
....................
..OBBBLLLLLLLLBBBO..
..OBBOBBBOOBBBOBBO..
..OO_O_OO__OO_O_OO..
"""},
    "robot": {"coat": {"B": (178, 190, 206), "O": (66, 76, 100), "L": (222, 232, 242), "P": (110, 215, 255), "D": (110, 124, 150)}, "top": """
.........R..........
.........g..........
..OOOOOOOOOOOOOOOO..
""", "after": """
....................
....................
....................
....................
....................
.g................g.
"""},
    "mushroom": {"coat": {"B": (248, 230, 205), "O": (122, 70, 62), "L": (255, 246, 232), "D": (226, 60, 70)}, "top": """
....OOOOOOOOOOOO....
..OORRWWRRRRRWRROO..
.ORRRWWRRRRWWRRRRRO.
.OOOOOOOOOOOOOOOOOO.
"""},
    "axolotl": {"coat": {"B": (255, 174, 194), "O": (176, 84, 122), "L": (255, 226, 234), "P": (255, 104, 150), "D": (240, 110, 160)}, "top": """
....................
....................
....................
""", "after": """
....................
....................
....................
PP................PP
.P................P.
PP................PP
"""},
    "dragon": {"coat": {"B": (120, 204, 156), "O": (40, 98, 92), "L": (232, 246, 204), "D": (60, 152, 132)}, "top": """
...L............L...
...LL..........LL...
...OL..........LO...
"""},
}

FACES = {
    "open": """
BBWWEBBBBWWEBB
BBWEEBBBBWEEBB
BPEEEBMMBEEEPB
""",
    "blink": """
BBBBBBBBBBBBBB
BBEEEBBBBEEEBB
BPBBBBMMBBBBPB
""",
    "happy": """
BBBEBBBBBBEBBB
BBEBEBBBBEBEBB
BPBBBMMMMBBBPB
BBBBBMTTMBBBBB
""",
    "chew": """
BBWWEBBBBWWEBB
BBWEEBBBBWEEBB
BPEEEMMMMEEEPB
""",
    "asleep": """
BBBBBBBBBBBBBB
BBEBEBBBBEBEBB
BPBEBBMMBBEBPB
""",
    "full": """
BBWWEBBBBWWEBB
BBWEEBBBBWEEBB
BPEEEMMMMEEEPB
BBLLLLLLLLLLBB
""",
    "out": """
BBEBEBBBBEBEBB
BBBEBBBBBBEBBB
BBEBEBMMBEBEBB
BBBBBBTTBBBBBB
""",
}

# Things floating around the pet. Drawn over everything, never moved.
FLOATS = {
    "tokensA": """
....................
....................
....................
....................
y..................c
....................
.c................v.
....................
v..................y
""",
    "tokensB": """
....................
....................
....................
....................
...................v
c...................
..................y.
.y..................
..................c.
""",
    "zzzA": """
.................ZZZ
..................Z.
.................ZZZ
""",
    "zzzB": """
....................
..................ZZ
..................ZZ
""",
    "sweat": """
....................
....................
....................
...................S
...................S
""",
    "sparkA": """
y..................W
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
W..................y
""",
    "sparkB": """
....................
.W................y.
....................
....................
....................
....................
....................
....................
....................
....................
.y................W.
""",
    "heartsA": """
R.R..............R.R
RRR..............RRR
.R................R.
""",
    "heartsB": """
....................
R.R..............R.R
.R................R.
""",
}

# Things a pet wears, drawn for the kid's head. Smaller bodies wear them lower.
ITEMS = {
    "headphones": """
....................
.......KKKKKK.......
....................
....................
.KK..............KK.
.Kc..............cK.
.KK..............KK.
""",
    "wizard": """
.........vv.........
........vyvv........
......vvvvvvvv......
""",
    "crown": """
.......y.yy.y.......
.......yRyycy.......
""",
    "tophat": """
........KKKK........
........RRRR........
......KKKKKKKK......
""",
    "bandage": """
....................
....................
....................
...........WWW......
...........WRW......
""",
    "sweatband": """
....................
....................
....................
...RRRRRRWWRRRRR....
""",
    "bow": """
............R...R...
............RRyRR...
............R...R...
""",
    "flower": """
....P...............
...PyP..............
....P...............
""",
    "sprout": """
........jj.j........
.........jj.........
.........j..........
""",
    "propeller": """
......cccKRRR.......
........yyyy........
.......RRRRRR.......
""",
    "halo": """
.......yyyyyy.......
....................
""",
    "flame": """
..........F.........
.........FyF........
........FFyFF.......
""",
    "star": """
.........yy.........
.......yyWWyy.......
.........yy.........
""",
    # Not something to collect: only the pet in first place on the leaderboard wears it.
    "champion": """
......y..yy..y......
......yy.yy.yy......
......yRyccyRy......
""",
}

EGG = """
....................
.........OO.........
.......OOLLOO.......
......OLLLLLLO......
.....OLLBBLLLLO.....
.....OLLBBLLLBO.....
....OLLLLLLLLLLO....
....OLLLLLBBLLLO....
....OLLBLLBBLLLO....
....OLLLLLLLLLLO....
.....OLLLLLLLLO.....
......OOOOOOOO......
"""
CRACKED = """
....................
.........OO.........
.......OOLLOO.......
......OLLLLLLO......
.....OLLBBLLLLO.....
.....OLOBLLOLBO.....
....OOLOLOOLOLOO....
....OLLOLLBBOLLO....
....OLLBLLBBLLLO....
....OLLLLLLLLLLO....
.....OLLLLLLLLO.....
......OOOOOOOO......
"""


STAGES = ("baby", "kid", "teen", "adult", "legend")
WIDTH, HEIGHT = 20, 12


def rows(picture, width=WIDTH):
    out = picture.strip("\n").split("\n")
    assert all(len(r) == width for r in out), [len(r) for r in out]
    return out


def lean(picture, by):
    """The same picture pushed sideways, for an egg that rocks."""
    return [("." * by + r)[:WIDTH] if by > 0 else (r[-by:] + "." * -by) for r in rows(picture)]


def parts():
    return {
        "colors": COLORS,
        "coats": COATS,
        "bodies": {name: {"face": b["face"], "lift": b["lift"], "art": rows(b["art"])} for name, b in BODIES.items()},
        "growth": {name: rows(p) for name, p in GROWTH.items()},
        "species": {name: {"coat": one["coat"], "top": rows(one["top"]), "after": rows(one["after"]) if "after" in one else []}
                    for name, one in SPECIES.items()},
        "faces": {name: rows(p, 14) for name, p in FACES.items()},
        "floats": {name: rows(p) for name, p in FLOATS.items()},
        "items": {name: rows(p) for name, p in ITEMS.items()},
        "egg": [rows(EGG), lean(EGG, 1), rows(EGG), lean(EGG, -1)],
        "cracked": [rows(CRACKED), lean(CRACKED, 1), rows(CRACKED), lean(CRACKED, -1)],
    }


def compose(art, species, stage, face, item=None, floats=(), coats=()):
    """The same steps the plugin takes, kept here so the sheet shows what the plugin will draw."""
    kind = art["species"][species]
    body = art["bodies"]["baby" if stage == "baby" else "grown"]
    px = [list(r) for r in body["art"]]

    def stamp(picture, top=0, left=0, solid=False):
        for dy, line in enumerate(picture or []):
            for dx, ch in enumerate(line):
                if 0 <= top + dy < HEIGHT and (solid or ch != "."):
                    px[top + dy][left + dx] = "." if ch == "_" else ch

    if stage != "baby":
        stamp(kind["top"])
        stamp(art["growth"].get("adult" if stage == "legend" else stage))
    stamp(art["faces"][face], body["face"], 3, solid=True)
    if stage != "baby":
        stamp(kind["after"])
    stamp(art["items"].get(item), body["lift"])
    for name in floats:
        stamp(art["floats"][name])
    palette = dict(art["colors"])
    for coat in [kind["coat"], art["coats"]["legend"] if stage == "legend" else {}, *[art["coats"][c] for c in coats]]:
        palette.update(coat)
    return [[palette.get(ch) for ch in r] for r in px]


def png(path, tiles, across, zoom=8, gap=2):
    down = -(-len(tiles) // across)
    w, h = across * (WIDTH + gap) * zoom, down * (HEIGHT + gap) * zoom
    back = (24, 24, 30)
    canvas = [[back] * w for _ in range(h)]
    for i, tile in enumerate(tiles):
        ox, oy = (i % across) * (WIDTH + gap) * zoom + zoom, (i // across) * (HEIGHT + gap) * zoom + zoom
        for y, row in enumerate(tile):
            for x, c in enumerate(row):
                if c:
                    for yy in range(zoom):
                        canvas[oy + y * zoom + yy][ox + x * zoom:ox + (x + 1) * zoom] = [tuple(c)] * zoom
    raw = b"".join(b"\0" + bytes(v for px in row for v in px) for row in canvas)
    chunk = lambda kind, data: struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data))
    Path(path).write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0))
                           + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))


def sheet(art, path):
    tiles = []
    for species in art["species"]:
        tiles += [compose(art, species, stage, "open") for stage in STAGES]
        tiles += [compose(art, species, "kid", "happy", floats=["tokensA"]), compose(art, species, "adult", "asleep", floats=["zzzA"]),
                  compose(art, species, "kid", "out", coats=["fainted"]), compose(art, species, "kid", "open", item="crown"),
                  compose(art, species, "teen", "open", coats=["shiny"])]
    png(path, tiles, 10, zoom=6)


def docs(art, folder):
    """The pictures the README shows."""
    folder.mkdir(exist_ok=True)
    png(folder / "animals.png", [compose(art, name, "teen", "open") for name in art["species"]], 5, zoom=10)
    png(folder / "growing.png", [compose(art, "duck", stage, "open") for stage in STAGES], 5, zoom=10)
    png(folder / "collection.png", [compose(art, "blob", "kid", "open", item=name) for name in art["items"]], 7, zoom=8)
    png(folder / "moods.png", [compose(art, "cat", "kid", "happy", floats=["tokensA"]), compose(art, "cat", "kid", "asleep", floats=["zzzA"]),
                               compose(art, "cat", "kid", "full", floats=["sweat"]), compose(art, "cat", "kid", "out", coats=["fainted"]),
                               compose(art, "cat", "kid", "happy", floats=["heartsA"])], 5, zoom=10)


if __name__ == "__main__":
    art = parts()
    here = Path(__file__).resolve().parent
    # The plugin draws the pets, and so does the leaderboard's web page: both get the same parts.
    for target, declare in ((here / "vramagotchi" / "hooks" / "register.tsx", "const ART: Art = "),
                            (here.parent / "leaderboard" / "web" / "index.html", "const ART = ")):
        source = target.read_text()
        start, end = source.index("// ART-START"), source.index("// ART-END")
        target.write_text(source[:start] + "// ART-START (written by claude-plugin/build.py)\n" + declare + json.dumps(art) + "\n" + source[end:])
    print("parts written:", {k: len(v) for k, v in art.items()})
    docs(art, here.parent / "docs")
    if len(sys.argv) > 1:
        sheet(art, sys.argv[1])
        print("sheet saved:", sys.argv[1])
